### ISSUE TITLE
[Website] services 2.0

### ISSUE THREAD

**Issue by noelmace** [fullwebdev/fullwebdev#134]
# Website - Epic

## Detailed Description

Remaning tasks from #101 :

### Top priorities

- [ ] contact form
- [ ] consulting: details
- [ ] Trainings & Lectures: details ("custom solutions")

### Important

- [ ] newsletter: interest groups
- [ ] coaching: contributing to "common pot" :arrow_right: Open Collective / LiberaPay / Patreon / Flattr / ?
- [ ] workshops: sessions (calendly / eventbrite / ?)
- [ ] Trainings & Lectures: catalog
- [ ] DevRel details
- [ ] Instructional Engineering details

### Optionnals

- [ ] coaching: details (princing, etc.)
- [ ] workshops: details
- [ ] newsletter: details
- [ ] calendly events summary ?
- [ ] donation platforms summary ?
